/**
 * Mock wellness place seed data.
 *
 * Includes:
 *  - ≥3 valid destinations per pillar so each filter view has real density
 *  - 2 intentional "trap" entries (generic municipal park, generic gym)
 *    used to demonstrate the negative keyword filter in action
 */

import type { WellnessPlace } from "./types";

export const MOCK_WELLNESS_PLACES: readonly WellnessPlace[] = [
  // --- Mindfulness (5) ---
  {
    id: "mind-1",
    name: "Kotonoha Tea House",
    distance: "0.3 mi",
    rating: 4.8,
    pillar: "Mindfulness",
    contextualWhy: "Quiet tea ritual with a real chance to slow down.",
    validationTag: "Herbal Tea Sanctuary",
    googlePlaceType: "spa",
    coordinates: { lat: 40.7295, lng: -73.9965 },
    tags: ["tea house", "herbal", "sanctuary"],
  },
  {
    id: "mind-2",
    name: "Eastside Zen Meditation Center",
    distance: "0.5 mi",
    rating: 4.7,
    pillar: "Mindfulness",
    contextualWhy: "Drop-in guided meditation block starts every 30 minutes.",
    validationTag: "Meditation Center",
    googlePlaceType: "spa",
    coordinates: { lat: 40.7310, lng: -73.9912 },
    tags: ["zen", "meditation"],
  },
  {
    id: "mind-3",
    name: "Cedar Mindfulness Trail",
    distance: "0.8 mi",
    rating: 4.6,
    pillar: "Mindfulness",
    contextualWhy: "A shaded loop with natural places to pause.",
    validationTag: "Mindfulness Trail",
    googlePlaceType: "park",
    coordinates: { lat: 40.7345, lng: -73.9890 },
    tags: ["trail", "mindfulness"],
  },
  {
    id: "mind-4",
    name: "Sora Sound Healing Sanctuary",
    distance: "1.1 mi",
    rating: 4.9,
    pillar: "Mindfulness",
    contextualWhy: "A sound bath built for getting quiet without effort.",
    validationTag: "Sound Healing Sanctuary",
    googlePlaceType: "spa",
    coordinates: { lat: 40.7361, lng: -73.9855 },
    tags: ["sound healing", "sanctuary"],
  },
  {
    id: "mind-5",
    name: "Stonework Labyrinth Garden",
    distance: "0.7 mi",
    rating: 4.5,
    pillar: "Mindfulness",
    contextualWhy: "A short walking labyrinth when sitting still feels hard.",
    validationTag: "Zen Garden",
    googlePlaceType: "park",
    coordinates: { lat: 40.7280, lng: -73.9930 },
    tags: ["labyrinth", "garden", "zen"],
  },

  // --- Longevity (4) ---
  {
    id: "long-1",
    name: "The Thermal Bathhouse",
    distance: "0.6 mi",
    rating: 4.8,
    pillar: "Longevity",
    contextualWhy: "A warm/cold circuit for a deeper recovery reset.",
    validationTag: "Bathhouse",
    googlePlaceType: "spa",
    coordinates: { lat: 40.7300, lng: -73.9900 },
    tags: ["bathhouse", "thermal", "sauna"],
  },
  {
    id: "long-2",
    name: "Aether Float Center",
    distance: "0.9 mi",
    rating: 4.9,
    pillar: "Longevity",
    contextualWhy: "A float session for quiet recovery with no screens.",
    validationTag: "Float Tank",
    googlePlaceType: "health",
    coordinates: { lat: 40.7320, lng: -73.9870 },
    tags: ["float", "recovery"],
  },
  {
    id: "long-3",
    name: "Northstar Cryotherapy & Sauna",
    distance: "1.3 mi",
    rating: 4.6,
    pillar: "Longevity",
    contextualWhy: "A short cold session when you want a sharp reset.",
    validationTag: "Cryotherapy",
    googlePlaceType: "health",
    coordinates: { lat: 40.7370, lng: -73.9820 },
    tags: ["cryo", "sauna"],
  },
  {
    id: "long-4",
    name: "Onsen Cold Plunge Studio",
    distance: "0.4 mi",
    rating: 4.7,
    pillar: "Longevity",
    contextualWhy: "Cold-plunge bays make this easy to do without planning.",
    validationTag: "Cold Plunge",
    googlePlaceType: "spa",
    coordinates: { lat: 40.7285, lng: -73.9945 },
    tags: ["plunge", "onsen"],
  },

  // --- Somatic Movement (4) ---
  {
    id: "soma-1",
    name: "Soma Yoga Shala",
    distance: "0.4 mi",
    rating: 4.9,
    pillar: "Somatic Movement",
    contextualWhy: "A slow-flow class that wakes the body up gently.",
    validationTag: "Yoga Shala",
    googlePlaceType: "gym",
    coordinates: { lat: 40.7290, lng: -73.9950 },
    tags: ["shala", "yoga"],
  },
  {
    id: "soma-2",
    name: "Reformer Pilates Studio West",
    distance: "0.7 mi",
    rating: 4.7,
    pillar: "Somatic Movement",
    contextualWhy: "A focused reformer session without a long time commitment.",
    validationTag: "Pilates Studio",
    googlePlaceType: "gym",
    coordinates: { lat: 40.7305, lng: -73.9905 },
    tags: ["pilates", "studio"],
  },
  {
    id: "soma-3",
    name: "Holistic Movement Collective",
    distance: "1.0 mi",
    rating: 4.6,
    pillar: "Somatic Movement",
    contextualWhy: "Mobility and breath work in one guided class.",
    validationTag: "Holistic Movement",
    googlePlaceType: "gym",
    coordinates: { lat: 40.7335, lng: -73.9880 },
    tags: ["movement", "holistic"],
  },
  {
    id: "soma-4",
    name: "Riverbank Mindfulness Trail",
    distance: "0.5 mi",
    rating: 4.5,
    pillar: "Somatic Movement",
    contextualWhy: "Out-and-back trail loop — paced for a 25-minute reset.",
    validationTag: "Mindfulness Trail",
    googlePlaceType: "park",
    coordinates: { lat: 40.7250, lng: -73.9980 },
    tags: ["trail", "mindfulness"],
  },

  // --- Nourishment (4) ---
  {
    id: "nour-1",
    name: "Adaptogen Apothecary Cafe",
    distance: "0.3 mi",
    rating: 4.8,
    pillar: "Nourishment",
    contextualWhy: "Tea and food that feel calming rather than heavy.",
    validationTag: "Apothecary Cafe",
    googlePlaceType: "cafe",
    coordinates: { lat: 40.7298, lng: -73.9960 },
    tags: ["apothecary", "adaptogenic"],
  },
  {
    id: "nour-2",
    name: "Mycelium Functional Mushroom Bar",
    distance: "0.5 mi",
    rating: 4.7,
    pillar: "Nourishment",
    contextualWhy: "A gentler clarity boost without leaning on another coffee.",
    validationTag: "Mushroom Cafe",
    googlePlaceType: "cafe",
    coordinates: { lat: 40.7315, lng: -73.9915 },
    tags: ["mushroom", "functional", "tonic"],
  },
  {
    id: "nour-3",
    name: "Greenfield Organic Market",
    distance: "0.4 mi",
    rating: 4.6,
    pillar: "Nourishment",
    contextualWhy: "A quick whole-foods stop if you need something grounding.",
    validationTag: "Organic Market",
    googlePlaceType: "store",
    coordinates: { lat: 40.7288, lng: -73.9955 },
    tags: ["market", "herbal"],
  },
  {
    id: "nour-4",
    name: "Vital Pulse Adaptogenic Juice Bar",
    distance: "0.6 mi",
    rating: 4.5,
    pillar: "Nourishment",
    contextualWhy: "A quick juice stop that still feels restorative.",
    validationTag: "Adaptogenic Juice Bar",
    googlePlaceType: "food",
    coordinates: { lat: 40.7308, lng: -73.9925 },
    tags: ["adaptogenic", "juice"],
  },

  // --- Generic traps (intentional pollution to demo the negative filter) ---
  {
    id: "trap-1",
    name: "Governors Park",
    distance: "0.5 mi",
    rating: 4.0,
    // Categorized as Somatic Movement by an upstream raw fetch, but the
    // negative filter will reject it because the name lacks any whitelist
    // token (no trail/garden/labyrinth/shala/etc.). Demonstrates the rule.
    pillar: "Somatic Movement",
    contextualWhy: "Standard urban grass field.",
    validationTag: "Generic Park",
    googlePlaceType: "park",
    coordinates: { lat: 40.7270, lng: -73.9990 },
    tags: [],
  },
  {
    id: "trap-2",
    name: "Westside Generic Gym",
    distance: "0.8 mi",
    rating: 3.8,
    // Categorized as Somatic Movement by raw fetch; name has no whitelist
    // token (no shala/studio/pilates/yoga/movement/climbing/trail). Filtered.
    pillar: "Somatic Movement",
    contextualWhy: "Standard 24-hour commercial gym.",
    validationTag: "Generic Gym",
    googlePlaceType: "gym",
    coordinates: { lat: 40.7340, lng: -73.9860 },
    tags: [],
  },
];
